components/app_component/config/routes.rb
AppComponent::Engine.routes.draw do
  root to: 'static_pages#index'

  mount Pictures::Engine, at: Pictures::Engine.mount_path, as: :pictures_engine

  get :contacts,  to: 'static_pages#contacts'
  get :timetable, to: 'static_pages#timetable'
  get :seminar,   to: 'static_pages#seminar'
  get :donate,    to: 'static_pages#donate'

  resources :articles, :events
  resources :contact_forms, only: :create
  resources :donations, only: :create do
    post :confirm, on: :collection
  end

  namespace :admins do
    root to: 'dashboard#index'
    resources :roles, except: [:new, :edit]
    resources :users, except: [:new, :edit, :destroy]
    resources :static_pages, except: [:new, :edit, :destroy]
  end

  devise_for :users, class_name: 'AppComponent::User', controllers: { sessions: 'app_component/sessions' }
  devise_for :admins, class_name: 'AppComponent::Admin', controllers: { sessions: 'app_component/admins/sessions' }
  mount Ckeditor::Engine => '/ckeditor'
end

components/app_component/app/views/layouts/_banner.html.slim
.interactive-slider-v2.interactive-slider-custom
  .container
    h1= t('.main_text')
    p= t('.subtext')

components/app_component/app/views/layouts/_copyright.html.slim
.copyright
  .container
    .row
      .col-md-10
        p= t('.rights_reserved')
      .col-md-2
        ul.footer-socials.list-inline
          li
            a.tooltips[data={'original-title': 'Facebook', placement: 'top', toggle: 'tooltip'}
                       href==t('.facebook.link') title==t('.facebook.title')]
              i.fa.fa-facebook
          li
            a.tooltips[data={'original-title': 'Google Plus', placement: 'top', toggle: 'tooltip'}
                       href=t('.google_plus.link') title==t('.google_plus.title')]
              i.fa.fa-google-plus

components/app_component/app/views/layouts/_footer.html.slim
.footer
  .container
    .row
      .col-md-3.md-margin-bottom-40
        br
        br
        p= t('.about_1')
        p= t('.about_2')
      .col-md-3.md-margin-bottom-40
        .posts
          .headline
            h2= t('.latest_posts')
          ul.list-unstyled.latest-list
            - AppComponent::Page.latest(5).each do |page|
              li
                = link_to page.title, page
                small
      .col-md-3.md-margin-bottom-40
        .headline
          h2= t('.useful_links')
        ul.list-unstyled.link-list
          li
            = link_to t('layouts.header.timetable'), timetable_path
            i.fa.fa-angle-right
          li
            = link_to t('layouts.header.seminar'), seminar_path
            i.fa.fa-angle-right
          li
            = link_to t('layouts.header.articles'), articles_path
            i.fa.fa-angle-right
          li
            = link_to t('layouts.header.events'), events_path
            i.fa.fa-angle-right
          li
            = link_to t('layouts.header.donate'), donate_path
            i.fa.fa-angle-right
          li
            = link_to t('layouts.header.contacts'), contacts_path, data: { no_turbolink: true }
            i.fa.fa-angle-right
      .col-md-3.md-margin-bottom-40
        .headline
          h2= t('.contacts')
        address.md-margin-bottom-40
          = t('.address')
          br
          = "#{t('.phone.title')}: #{t('.phone.value')}"
          br
          = "#{t('.email.title')}:"
          a<[href="mailto:#{t('.email.value')}"]= t('.email.value')

components/app_component/app/views/layouts/_header.html.slim
.navbar.navbar-default.mega-menu role='navigation'
  .container
    .navbar-header
      button.navbar-toggle data={target: '.navbar-responsive-collapse', toggle: 'collapse'} type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      - if current_page?(root_path)
        span.navbar-brand.logo-link= t('.listvytsia')
      - else
        a.navbar-brand.logo-link[href=root_path]= t('.listvytsia')
    .collapse.navbar-collapse.navbar-responsive-collapse
      ul.nav.navbar-nav
        li class=('active' if current_page?(timetable_path))
          = link_to t('.timetable'), timetable_path
        li class=('active' if current_page?(seminar_path))
          = link_to t('.seminar'), seminar_path
        li class=('active' if current_page?(articles_path))
           = link_to t('.articles'), articles_path
        - if AppComponent::Event.published.exists?
          li class=('active' if current_page?(events_path))
             = link_to t('.events'), events_path
        li class=('active' if current_page?(donate_path))
           = link_to t('.donate'), donate_path
        li class=('active' if current_page?(contacts_path))
          = link_to t('.contacts'), contacts_path, data: { no_turbolink: true }

components/app_component/app/views/layouts/_login_info.html.slim
.topbar-v3
  .container
    .row
      .col-sm-6.col-sm-offset-6
        ul.list-inline.right-topbar.pull-right
          li
            = t('.logged_in_as')
            span<
              strong= current_user.email
          li
            ||
          li
            = link_to t('.log_out'), destroy_user_session_path(current_user), method: :delete

components/app_component/app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

components/app_component/app/views/layouts/admin.html.slim
doctype html
html lang==I18n.locale
  head
    title= content_for?(:title) ? yield(:title) : t('site_info.name')
    meta name="description" content="#{content_for?(:description) ? yield(:description) : t('site_info.name')}"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    == favicon_link_tag 'favicon.ico'
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body class= "admin #{controller_name} #{action_name}_page"
    .wrapper
      .header-v5
        == render 'layouts/admin/login_info'
        == render 'layouts/admin/navigation'
      .container.content.content-custom
        == render 'layouts/messages'
        .col-md-7
          == yield
      .footer-v1
        == render 'layouts/admin/footer'
    == javascript_include_tag 'admin', 'data-turbolinks-track' => true

components/app_component/app/views/layouts/public.html.slim
doctype html
html lang==I18n.locale
  head
    title= content_for?(:title) ? "#{yield(:title)} | #{t('site_info.name')}" : t('site_info.name')
    meta name="description" content="#{content_for?(:description) ? yield(:description) : t('site_info.name')}"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    == favicon_link_tag 'favicon.ico'
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body class= "#{controller_name} #{action_name}_page"
    .wrapper
      .header-v5
        == render 'layouts/admin/login_info' if current_admin
        == render 'layouts/login_info' if current_user
        == render 'layouts/header'
      - if current_page?(root_path)
        == render 'layouts/messages'
        == render 'layouts/banner'
      .container.content.content-custom
        == render 'layouts/messages' unless current_page?(root_path)
        == yield
      .footer-v1
        == render 'layouts/footer'
        == render 'layouts/copyright'
    == javascript_include_tag 'public', 'data-turbolinks-track' => true
    == yield :script