components/app_component/config/routes.rb
AppComponent::Engine.routes.draw do
  root to: 'static_pages#index'

  mount Pictures::Engine, at: Pictures::Engine.mount_path, as: :pictures_engine

  get :contacts,  to: 'static_pages#contacts'
  get :timetable, to: 'static_pages#timetable'
  get :seminar,   to: 'static_pages#seminar'
  get :donate,    to: 'static_pages#donate'

  resources :articles, :events
  resources :contact_forms, only: :create
  resources :donations, only: :create do
    post :confirm, on: :collection
  end

  namespace :admins do
    root to: 'dashboard#index'
    resources :roles, except: [:new, :edit]
    resources :users, except: [:new, :edit, :destroy]
    resources :static_pages, except: [:new, :edit, :destroy]
  end

  devise_for :users, class_name: 'AppComponent::User', controllers: { sessions: 'app_component/sessions' }
  devise_for :admins, class_name: 'AppComponent::Admin', controllers: { sessions: 'app_component/admins/sessions' }
  mount Ckeditor::Engine => '/ckeditor'
end

components/app_component/app/views/layouts/admin/_footer.html.slim
.footer
  .container
    .row

components/app_component/app/views/layouts/admin/_login_info.html.slim
.topbar-v3.primary-background-color
  .container
    .row
      .col-md-6.col-sm-6
        ul.list-inline.right-topbar
          li= link_to t('.dashboard'), admins_root_path
      .col-md-6.col-sm-6
        ul.list-inline.right-topbar.pull-right
          li
            = t('.logged_in_as')
            span<
              strong= current_admin.email
          li
            ||
          li
            = link_to t('.log_out'), destroy_admin_session_path(current_admin), method: :delete

components/app_component/app/views/layouts/admin/_navigation.html.slim
.navbar.navbar-default.mega-menu role='navigation'
  .container
    .navbar-header
      button.navbar-toggle data={target: '.navbar-responsive-collapse', toggle: 'collapse'} type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand.logo-link[href=root_path]= t('site_info.name')
    .collapse.navbar-collapse.navbar-responsive-collapse
      ul.nav.navbar-nav
        li= link_to AppComponent::Role.human_list_name, '#/roles'
        li= link_to AppComponent::User.human_list_name, '#/users'
        li= link_to AppComponent::StaticPage.human_list_name, '#/static_pages'